services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    container_name: express-server
    ports:
      - "4000:4000"
    networks:
      - fullstack-net
    restart: unless-stopped

  client:
    build: 
      context: ./client
      args:
        VITE_API_URL: http://localhost:4000/api
    container_name: react-client
    ports:
      - "5173:3000"
    networks:
      - fullstack-net
    restart: unless-stopped
    depends_on:
      - server

networks:
  fullstack-net:
    driver: bridge
